### ISSUE TITLE
Should optionally pull in function and file documentation

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#140]
So can generate D documentation if that's what is wanted

**Comment by atilaneves** [comment]
One isn't supposed to look at the translated source code. The documentation to be consulted should be of the original C or C++ source code.

It'd be nearly impossible to match the "documentation" (i.e. comments) with the original cursors since they their order gets changed in the process of translation (because of libclang oddities).

If original code has any documentation (probably Doxygen), then generating it from there would be the ideal.

**Comment by Laeeth** [comment]
Libclang can get documentation comments attached to functions.

And since dpp isn't perfect one ought to consider need to read generated source for debugging problems.

**Comment by aminya** [comment]
Can DPP preserve the documentation before functions? IDE's data tips rely on this documentation, and if DPP can preserve them, we will have data tips for the generated files.
```c
/** some docs here */
void some_function()
```
