### ISSUE TITLE
freetype2: Untranslatable cursor errors

### ISSUE THREAD

**Issue by dewf** [atilaneves/dpp#159]
Debian 9 / DMD 2.084 

1 minor issue, manually worked around: Freetype2 uses a header thing where the includes are themselves macro definitions:
```
#include <ft2build.h>
#include FT_FREETYPE_H // actually <freetype/freetype.h>
```
No biggie, just used the explicit version. But then that gives me:
```
Untranslatable cursor Cursor(MacroDefinition, "__bswap_16", Type(Invalid, ""))
Untranslatable cursor Cursor(MacroDefinition, "__bswap_32", Type(Invalid, ""))
Untranslatable cursor Cursor(MacroDefinition, "__bswap_64", Type(Invalid, ""))
```

Expanded version:
```
Untranslatable cursor Cursor(MacroDefinition, "__bswap_16", Type(Invalid, ""))
msg: Not valid D:
------------
#define __bswap_16(x) \
     (__extension__							      \
      ({ unsigned short int __v, __x = (unsigned short int) (x);	      \
	 if (__builtin_constant_p (__x))				      \
	   __v = __bswap_constant_16 (__x);				      \
	 else								      \
	   __asm__ ("rorw $8, %w0"					      \
		    : "=r" (__v)					      \
		    : "0" (__x)						      \
		    : "cc");						      \
	 __v; }))

------------

sourceRange: SourceRange("/usr/include/x86_64-linux-gnu/bits/byteswap-16.h", 25:11, 35:11)
children: []


Untranslatable cursor Cursor(MacroDefinition, "__bswap_32", Type(Invalid, ""))
msg: Not valid D:
------------
#define __bswap_32(x) \
      (__extension__							      \
       ({ unsigned int __v, __x = (x);					      \
	  if (__builtin_constant_p (__x))				      \
	    __v = __bswap_constant_32 (__x);				      \
	  else								      \
	    __asm__ ("bswap %0" : "=r" (__v) : "0" (__x));		      \
	  __v; }))

------------

sourceRange: SourceRange("/usr/include/x86_64-linux-gnu/bits/byteswap.h", 58:12, 65:12)
children: []


Untranslatable cursor Cursor(MacroDefinition, "__bswap_64", Type(Invalid, ""))
msg: Not valid D:
------------
#define __bswap_64(x) \
     (__extension__							      \
      ({ __uint64_t __v, __x = (x);					      \
	 if (__builtin_constant_p (__x))				      \
	   __v = __bswap_constant_64 (__x);				      \
	 else								      \
	   __asm__ ("bswap %q0" : "=r" (__v) : "0" (__x));		      \
	 __v; }))

------------

sourceRange: SourceRange("/usr/include/x86_64-linux-gnu/bits/byteswap.h", 114:11, 121:11)
children: []
```

**Comment by atilaneves** [comment]
> where the includes are themselves macro definitions

Sigh. I hate other people's code. I also hate my code too, but still.

> No biggie, just used the explicit version. But then that gives me:

I don't see how any of those macros are usable from D without extensive translation. I'm not sure it's doable by a machine.

**Comment by trikko** [comment]
About include: doesn't DPP work on preprocessed c code? 

I understand you're going to lose consts #define and macro, but you can try to translate them in a second run/step. Am I wrong?

**Comment by Laeeth** [comment]
It's not possible to translate C code in the general case without making a C to D translator.  That's a broader scope than I think Atila had in mind for dpp, but I do think that this is worth doing at some point.  c2rust had a several million dollar grant supporting it, and that was a rewrite, so it's by no means a trivial endeavour.

however looking at the structure of c2rust we can actually hitch a ride on the work they have done.  they have a c++ front end that dumps the AST in a serialised format in what I think would be a more convenient format than you will get from libclang naturally.  we can use that part of it and then just translate the C AST to D.  That ought to be a much easier job than translating C to unsafe Rust because C and D semantics are very similar.  If you have a pointer within a struct to itself then maybe it's going to require some manual work, but otherwise I think a C to D translator is straightforward, though a daunting amount of work to do.

It's a matter of time before the Rust guys have parts of linux translated to Rust I suppose as a proof of concept.  I think there would be a community and ecosystem benefit from being able to do the same sort of thing, and it really would drive the point home about the usefulness of betterC if you could just translate C code and run it without using or even linking the GC.

Atila's view is that there is no need for  a C to D translator - you have C compilers for compiling C code.  But in practice I think it is valuable to be able to have an integrated codebase in D when the C code you are translating is mature and there aren't going to be frequent new releases.  So I am thinking about sponsoring a C to D translator for Symmetry autumn of code next year.

Anyway, given a C to D translator then translating macros is possible in many more cases.  Without building a C to D translator then in the general case it's definitely not possible.

**Comment by atilaneves** [comment]
Translating C macros like the ones above is either extremely difficult or downright impossible depending on the macro. C macros aren't C code - they're macro code, which is a different language that does text substitution and nothing else. Such macros written to generate C code don't have an AST - they're not C code yet! What code will be generated depends on the surrounding C code in the actual program.

As a human I can infer what `__bswap_64` does and probably write a similar macro (or template mixin / string mixin). As a programmer, I have no idea how to figure out how a string of characters should be translated in the general case. If there are braces, is it for struct initialisation? A function definition? There's no way to know.

**Comment by atilaneves** [comment]
@trikko:

> About include: doesn't DPP work on preprocessed c code?

Mostly, yes. But it also attempts to translate macros, with some of them being available for usage in the .dpp file verbatim.

> I understand you're going to lose consts #define and macro, but you can try to translate them in a second run/step. Am I wrong?

Nothing is lost. All constant `#define` macros are available. Look [at the tests](https://github.com/atilaneves/dpp/blob/051de5aa1a6e4ab02be3d3f6ff66715127afb31c/tests/it/c/compile/preprocessor.d).

**Comment by atilaneves** [comment]
Closing as I don't know how to write code to translate the macros in this example.

**Comment by dewf** [comment]
Thank you for looking into this, I appreciate it.
